vich_uploader:
    db_driver: orm

    mappings:
        gateaux:
            uri_prefix: /images/gateaux
            upload_destination: '%kernel.project_dir%/public/images/gateaux'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
